config/routes.rb
Rails.application.routes.draw do

  root 'players#index'
  resources :players

end

app/models/player.rb
class Player < ActiveRecord::Base

  def self.search(search)
      if search
        @players = Player.where(:team => search)
      else
        @players = Player.all
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  # New player
  def new
    @player = Player.new
  end

  # Create new player in the DB
  def create
    @player = Player.new player_params
    if @player.save
      redirect_to player_path(@player), notice: "Player Successfully created!"
    else
      flash[:alert] = "See error(s) below..."
      render :new
    end

  end

  # Index all Player
  def index
    # @players = Player.all
    @players = Player.search(params[:search])
  end

  # Display each player
  def show
    @player = Player.find params[:id]
  end

  def edit
    @player = Player.find params[:id]
  end

  # Update a player's info
  def update
    @player = Player.find params[:id]
    if @player.update player_params
      redirect_to player_path(@player), notice: "Player Successfully updated!"
    else
      flash[:alert] = "See error(s) below..."
      render :edit
    end
  end

  # Delete player record from the DB.
  def destroy
    @player = Player.find params[:id]
    @player.destroy
    redirect_to players_path
  end

  private

  def player_params
    params.require(:player).permit(:name, :age, :team)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Team</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/create.html.erb
<!-- Step 2) Create Player Form -->

<%= simple_form_for @player do |f| %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :age, label: "Age" %>
  <%= f.input :team, label: "Sports Team" %>
  <%= f.button :submit, "Create Player" %>
<% end %>

app/views/players/destroy.html.erb
<h1>Players#destroy</h1>
<p>Find me in app/views/players/destroy.html.erb</p>

app/views/players/edit.html.erb
<h1>Edit Player</h1>


<%= simple_form_for @player do |f| %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :age, label: "Age" %>
  <%= f.input :team, label: "Sports Team" %>
  <%= f.button :submit, "Edit" %>
<% end %>


  </div>

app/views/players/index.html.erb
<h1>Players Table</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Team</th>
  </tr>
  <% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= player.age %></td>
    <td><%= player.team %></td>
    <td><%= link_to "view", player_path(player) %></td>
    <td><%= link_to "edit", player_path(player) %></td>
    <td><%= link_to "destroy", player_path(player), method: :delete, data: {confirm: "Confirm Deletion?"} %></td>
  </tr>
  <% end %>
</table>

<br><br>

<%= form_tag players_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :team => nil %>
  </p>
<% end %>

<br><br>

<p><%= link_to "Create Player", new_player_path %></p>

app/views/players/new.html.erb
<!-- Step 2) Create Player Form -->

<%= simple_form_for @player do |f| %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :age, label: "Age" %>
  <%= f.input :team, label: "Sports Team" %>
  <%= f.button :submit, "Create Player" %>
<% end %>

app/views/players/show.html.erb
<h3><%= @player.name %></h3>
<p><%= @player.age %></p>
<p><%= @player.team %></p>

<br><br>

  <%= link_to "Back", root_path %>
  <%= link_to "Edit", edit_player_path(@player) %>
  <%= link_to "Delete", player_path(@player), method: :delete, data: {confirm: "Confirm Deletion?"} %>

app/views/players/update.html.erb
<h1>Players#update</h1>
<p>Find me in app/views/players/update.html.erb</p>